name: deahtNote
version: '1.0.0'
main: mx.angelDL_.Main
api-version: '1.21'
load: STARTUP
authors: [ angelDL_ ]
commands:
  missiontp:
    description: "Teletransportarse a misiones"
    usage: "/missiontp"
  s:
    description: Enviar mensaje anónimo a todos
    usage: /s <mensaje>
  m:
    description: Enviar susurro anónimo a un jugador
    usage: /m <jugador> <mensaje>
  debug:
    aliases:
      - dbg
  missiondebug:
    description: Debug de misiones
    usage: /missiondebug
  missionclear:
    description: Limpiar GUI de misiones
    usage: /missionclear
  testplayers:
    description: Test de selección de jugadores
    usage: /testplayers
  distributeroles:
    description: Distribuye roles entre los jugadores
    usage: /<command> [reset]